apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference-resources
spec:
  containers:
    - image: ymet/made_oi:v1
      name: online-inference-resources
      ports:
        - containerPort: 4242
      resources:
        requests:
          memory: "150M"
          cpu: "0.3"
        limits:
          memory: "300M"
          cpu: "0.5"