input_data_path: "source_data/heart_cleveland_upload.csv"
output_model_path: "results/models/model_rf.pkl"
metric_path: "results/metrics/metrics_rf.json"
splitting_params:
  val_size: 0.3
  random_state: 42
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
use_transformers:
  - "ohe"
