input_data_path: "source_data/heart_cleveland_upload.csv"
output_model_path: "results/models/model_log.pkl"
metric_path: "results/metrics/metrics_log.json"
splitting_params:
  val_size: 0.25
  random_state: 10
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"
use_transformers:
  - "ohe"
  - "square"
square_transformer_params:
  columns_for_square:
    - "trestbps"